### ISSUE TITLE
Encoding/decoding error when installing on debian jessie release.

### ISSUE THREAD

**Issue by rachellevanger** [rachellevanger/tda-d3-explorer#10]
Running `./install.sh` results in two errors:

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xaa in position 25: invalid start byte`

and

`SyntaxError: invalid or missing encoding declaration for 'bin/ImagePersistence'`

Environment is the debian jessie release included in the `jupyter/notebook-minimal` Docker base image. I do not get this error when installing on Mac OSX 10.11.3.

```
...
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/scripts-3.5
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/tokenize.py", line 392, in find_cookie
    line_string = line.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xaa in position 25: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    zip_safe=False)
  File "/opt/conda/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/conda/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/opt/conda/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/setuptools/command/install.py", line 67, in run
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/setuptools/command/install.py", line 109, in do_egg_install
  File "/opt/conda/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/conda/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/setuptools/command/bdist_egg.py", line 191, in run
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/setuptools/command/bdist_egg.py", line 147, in call_command
  File "/opt/conda/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/conda/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/setuptools/command/install_scripts.py", line 21, in run
  File "/opt/conda/lib/python3.5/distutils/command/install_scripts.py", line 43, in run
    self.run_command('build_scripts')
  File "/opt/conda/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/conda/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/opt/conda/lib/python3.5/distutils/command/build_scripts.py", line 50, in run
    self.copy_scripts()
  File "/opt/conda/lib/python3.5/distutils/command/build_scripts.py", line 82, in copy_scripts
    encoding, lines = tokenize.detect_encoding(f.readline)
  File "/opt/conda/lib/python3.5/tokenize.py", line 433, in detect_encoding
    encoding = find_cookie(first)
  File "/opt/conda/lib/python3.5/tokenize.py", line 397, in find_cookie
    raise SyntaxError(msg)
SyntaxError: invalid or missing encoding declaration for 'bin/ImagePersistence'
The command '/bin/sh -c cd tda-persistence-explorer && ./install.sh' returned a non-zero code: 1
```

**Comment by rachellevanger** [comment]
Changed from

`      scripts=['bin/ImagePersistence'], # includes binary executable
`

to

`      data_files=['bin/ImagePersistence'],` # includes binary executable
`
